from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    # path('admin_panel',views.admin_login,name='admin_login'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('orders',views.order,name='orders'),
    path('products',views.products,name='products'),
    path('add_products',views.add_products,name='add_products'),
    path('edit_products/<str:id>',views.edit_products,name='edit_products'),
    path('users',views.users,name='users'),
    path('categories',views.categories,name='categories'),
    path('add_categories',views.add_categories,name='add_categories'),
    path('edit_categories/<str:id>',views.edit_categories,name='edit_categories'),
    path('brands',views.brands,name='brands'),
    path('add_brands',views.add_brands,name='add_brands'),
    path('edit_brands/<str:id>',views.edit_brands,name='edit_brands'),
    path('coupons',views.coupons_view,name='coupons'),
    path('add_coupons',views.add_coupons,name='add_coupons'),
    path('payment_method',views.payment_method,name='payment_method'),
    path('banners',views.banners,name='banners'),
    path('add_banners',views.add_banners,name='add_banners'),
    # path('add_tyresize',views.add_tyresize,name='add_tyresize'),
    path('trash',views.trash,name='trash'),
    path('control/<str:id>',views.user_controlling,name='user_controlling'),
    path('product_control/<str:id>',views.product_controlling,name='product_controlling'),
    path('variants/<str:id>',views.variants,name='variants'),
    path('add_variants/<str:id>',views.add_variants,name='add_variants'),
    path('edit_variants/<str:id>',views.edit_variants,name='edit_variants'),
    path('product_control_tr/<str:id>',views.product_controlling_tr,name='product_controlling_tr'),
    path('variant_control/<str:id>',views.variant_controlling,name='variant_controlling'),
    path('category_control/<str:id>',views.category_controlling,name='category_controlling'),
    path('brand_control/<str:id>',views.brand_controlling,name='brand_controlling'),
    # path('logouttt',views.logouttt,name='logouttt'),
    path('about_order/<str:id>',views.about_order,name='about_order'),
    path('singleorderproduct/<str:id>',views.singleorderproduct,name='singleorderproduct'),
    path('edit_coupon/<str:id>',views.edit_coupon,name='edit_coupon'),
    path('couponlist/<str:id>',views.couponlist,name='couponlist'),
    path('deletecoupon/<str:id>',views.deletecoupon,name='deletecoupon'),
    path('offers',views.offers,name='offers'),
    path('category_offer',views.category_offer,name='category_offer'),
    path('product_offer',views.product_offer,name='product_offer'),
    path('edit_category_offer/<str:id>',views.edit_category_offer,name='edit_category_offer'),
    path('edit_product_offer/<str:id>',views.edit_product_offer,name='edit_product_offer'),
    path('banner_control/<str:id>',views.banner_controlling,name='banner_controlling'),
    path('reports',views.reports,name='reports'),
    # path('sales_report',views.salesreport,name='salesreport'),
    # path('stock_report',views.stockreport,name='stockreport'),
    # path('cancel_report',views.cancelreport,name='cancelreport'),
    path('pdf_download1/', views.DownloadPDF1.as_view(), name="pdf_download1"),
    path('pdf_download2/', views.DownloadPDF2.as_view(), name="pdf_download2"),
    path('pdf_download3/', views.DownloadPDF3.as_view(), name="pdf_download3"),
    path('download_exel',views.download_exel,name='download_exel'),
    path('download_exel1',views.download_exel1,name='download_exel1'),
    path('download_exel2',views.download_exel2,name='download_exel2'),

]

