apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres-container
          image: postgres:14.4-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
      #     volumeMounts:
      #       - name: postgres-volume-mount
      #         mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: postgres-volume-mount
      #     persistentVolumeClaim:
      #       claimName: postgres-pvc
