apiVersion: v1
kind: Service
metadata:
  name: cyclehub-srv
spec:
  type: NodePort
  selector:
    app: cyclehub
  ports:
    - name: cyclehub
      protocol: TCP
      port: 8000
      targetPort: 8000
