# Generated by Django 4.2.6 on 2023-11-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_address_is_liste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_liste',
            new_name='is_listed',
        ),
    ]
