# Generated by Django 4.2.6 on 2023-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_listed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_listed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TyreSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_size', models.IntegerField()),
                ('is_listed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('additional_images', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('is_listed', models.BooleanField(default=False)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.category')),
                ('tyre_size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.tyresize')),
            ],
        ),
    ]
