# Generated by Django 4.2.6 on 2023-10-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_remove_product_additional_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tyre_size_id',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TyreSize',
        ),
    ]
