# Generated by Django 4.2.6 on 2023-10-28 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tyre_size_id',
        ),
        migrations.AddField(
            model_name='tyresize',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
