# Generated by Django 4.2.6 on 2023-11-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_remove_product_offer_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('tyresize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tyresize')),
            ],
        ),
    ]
