# Generated by Django 4.2.6 on 2023-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
