# Generated by Django 4.2.6 on 2023-11-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
