# Generated by Django 4.2.6 on 2023-11-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_rename_is_liste_address_is_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_side', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(unique=True)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_status', models.CharField(default='Pending', max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.orders'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='tyrevariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tyresize'),
        ),
    ]
