# Generated by Django 4.2.6 on 2023-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_alter_ordereditems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fullproducttotal',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
