# Generated by Django 4.2.6 on 2023-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_orders_fullproducttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(default='Order Processing', max_length=100),
        ),
    ]
