# Generated by Django 4.2.6 on 2023-11-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_ordereditems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
