# Generated by Django 4.2.6 on 2023-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_ordereditems_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='status',
            field=models.CharField(default='Order Confirmed', max_length=100),
        ),
    ]
