# Generated by Django 4.2.6 on 2023-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0015_remove_ordereditems_is_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
