# Generated by Django 4.2.6 on 2023-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0018_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='coupon_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
