# Generated by Django 4.2.6 on 2023-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0024_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
