# Generated by Django 4.2.6 on 2023-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0025_alter_coupons_valid_from_alter_coupons_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
