# Generated by Django 4.2.6 on 2023-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0026_coupons_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
