# Generated by Django 4.2.6 on 2023-11-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0029_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='tyre_size',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
            preserve_default=False,
        ),
    ]
