# Generated by Django 4.2.6 on 2023-11-24 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0031_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
