# Generated by Django 4.2.6 on 2023-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0034_ordereditems_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
