# Generated by Django 4.2.6 on 2023-11-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0035_alter_category_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='user',
        ),
    ]
