# Generated by Django 4.2.6 on 2023-11-29 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0037_orders_remainingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
