# Generated by Django 4.2.6 on 2023-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0040_alter_banners_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_liste',
            field=models.BooleanField(default=False),
        ),
    ]
