# Generated by Django 4.2.6 on 2023-12-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0041_banners_is_liste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='is_liste',
            new_name='is_listed',
        ),
    ]
